config/routes.rb
Festivus::Application.routes.draw do
  resources :contacts
  resources :events

  devise_for :users

  resources :questionnaires, only: [:index, :show, :new, :create, :destroy] do
    match 'parse' => 'questionnaires#parse', as: "parse"
  end

  resources :instances, controller: "QuestionnaireInstances", only: [:show, :new, :create, :destroy]

  match 'instances' => 'questionnaire_instances#index', as: "instances"
  match 'instances/:id/send_reminder' => 'questionnaire_instances#remind', as: "send_reminder"

  as :user do
    get "/login" => "devise/sessions#new"
    delete "/logout" => "devise/sessions#destroy"
  end

  authenticated :user do
    root to: 'home#index', as: :authenticated_root
  end
  root to: 'home#index'

  mount Surveyor::Engine => '/surveyor', as: 'surveyor'

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

end

app/models/questionnaire_instance.rb
class QuestionnaireInstance < ActiveRecord::Base
  attr_accessible :due_date, :notification_count, :event_id, :questionnaire_id, :contact_id

  belongs_to :event
  belongs_to :questionnaire
  belongs_to :contact

  belongs_to :user
  belongs_to :response_set

  after_initialize :constructor

  #"constructor" is a mnemonic to represent what would be used in other languages
  def constructor
    return if !new_record?
    self.notification_count ||= 0 if self.has_attribute? :notification_count
  end

  def overdue?
    Time.now > self.due_date
  end

  #not collision safe, just a stop gap for time being
  def user_id
    self.user.id
  end

  def access_code
    rs = self.response_set
    surveyor.view_my_survey_path(response_set_code: rs.access_code, survey_code: rs.survey.access_code)
  end

  def complete?
    response_set.complete?
  end
end

app/controllers/questionnaire_instances_controller.rb
class QuestionnaireInstancesController < ApplicationController
  respond_to :html, :xml, :json

  def index
    @instances = QuestionnaireInstance.all.group_by(&:event)

    if !@instances.empty?
      respond_with(@instances)
    else
      render :empty
    end
  end

  def show
    @instance = QuestionnaireInstance.find(params[:id])
    @questionnaire = @instance.questionnaire #questionnaire as defined by us
    @response_set = @instance.response_set
    @survey = @response_set.survey #questionnaire or survey as defined by surveyor gem
    respond_with(@instance)
  end

  def new
    @instance = QuestionnaireInstance.new

    @questionnaires = Questionnaire.where(user_id: current_user)
    @events = Event.where(user_id: current_user)
    @contacts = Contact.where(user_id: current_user)
  end

  def create
    @questionnaire = Questionnaire.find(params[:questionnaire_instance][:questionnaire_id])

    datetime = DateTime.new(2013, 5, 1) #DateTime.strptime(params[:questionnaire_instance][:due_date], "%m/%d/%Y")
    p = params[:questionnaire_instance].merge({ due_date: datetime})
    @questionnaire_instance = QuestionnaireInstance.new(p)
    @questionnaire_instance.user = current_user

    @questionnaire_instance.response_set = QuestionnaireServices.create_surveyor_instance(@questionnaire, @questionnaire_instance)

    respond_with(@questionnaire_instance) do |format|
      if @questionnaire_instance.save
        flash[:notice] = 'Questionnaire instance was successfully created.'
        format.html { redirect_to instances_path }
        format.json { render json: instances_path, status: :created, location: @questionnaire_instance }
      else
        format.html { render action: "new" }
        format.json { render json: @questionnaire_instance.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @questionnaire_instance = QuestionnaireInstance.find(params[:id])
    @questionnaire_instance.destroy
    flash[:notice] = 'Questionnaire Instance was successfully removed.'
    redirect_to instances_path
  end

  def remind
    @instance = QuestionnaireInstance.find(params[:id])

    if QuestionnaireInstanceServices.send_reminder(@instance)
      flash[:notice] = "Reminder successfully sent to #{@instance.email}"
    else
      flash[:error] = "Reminder was not sent to #{@instance.email}"
    end

    redirect_to instances_path
  end
end

app/helpers/questionnaire_instances_helper.rb
module QuestionnaireInstancesHelper
end

app/views/questionnaire_instances/_form.html.haml
.well
  = form_for @instance, html: { id: 'instance-form' }, url: instances_path do |f|
    %fieldset
      .control-group
        = f.label :due_date, class: "control-label"
        .controls#datetime-picker.input-append
          = f.text_field :due_date
          %span.add-on
            %i{ :data => {:time_icon => "icon-time", :date_icon => "icon-calendar"} }

      .control-group
        = f.label :event, class: "control-label"
        .controls
          = f.select :event_id, @events.map {|e| [e.title, e.id]}, { prompt: "--Select Event--" }

      .control-group
        = f.label :contact, class: "control-label"
        .controls
          = f.select :contact_id, @contacts.map {|c| [c.name, c.id]}, { prompt: "--Select Contact--" }

      .control-group
        = f.label :questionnaire, class: "control-label"
        .controls
          = f.select :questionnaire_id, @questionnaires.map {|q| [q.title, q.id]}, { prompt: "--Select Questionnaire--" }

    .actions
      = f.submit 'Create', class: 'btn btn-primary'
      = link_to "Cancel", instances_path

- content_for :javascript do
  :javascript
    $(function() { $('#datetime-picker').datetimepicker({ language: 'en', pick12HourFormat: true }); });

app/views/questionnaire_instances/edit.html.haml
%h1 Editing Questionnaire Instance

= render 'form'
= link_to 'Show', @questionnaire_instance

app/views/questionnaire_instances/empty.html.haml
%h2 Oops
%h4
  No instances have been created. Click
  = link_to 'here', new_instance_path
  to create one.

app/views/questionnaire_instances/index.html.haml
%h1 Active Instances

- @instances.each do |event, instances|
  %h4{ class: "event-#{event.id}" }= event.title

  %table.table.table-striped.table-condensed
    %tr
      %th Questionnaire Name
      %th Event
      %th Contact
      %th Due date
      %th Completed
      %th Notification count
      %th Show
      %th Notify
      %th

    - instances.each do |instance|
      %tr
        %td
        %td= instance.event.title
        %td= instance.contact.name
        %td= instance.due_date
        %td= instance.complete?
        %td= instance.notification_count
        %td= link_to "Show", instance_path(instance)
        %td= link_to "Results", surveyor.view_my_survey_path(response_set_code: instance.response_set.access_code, survey_code: instance.response_set.survey.access_code)
        %td= link_to "Remind", send_reminder_path(instance), class: "btn btn-xs btn-default"
        %td= link_to 'Destroy', instance_path(instance), :method => :delete, :data => { :confirm => 'Are you sure?' }, class: "btn btn-xs btn-danger"

%br

= link_to 'New Instance', new_instance_path, class: "btn btn-primary"

app/views/questionnaire_instances/new.html.haml
%h1 New Questionnaire Instance

#basic-section
= render 'form'

#events-section


#contacts-section

#questionnaires-section

#review-section

app/views/questionnaire_instances/show.html.haml
%h5= @instance.event.title
%h5= @instance.user.email
%h2= @instance.questionnaire.title

%p
  %b Due date:
  = @instance.due_date

%p
  %b Notification count:
  = @instance.notification_count

%span
  Someday we'll put the rsults up on this page, for now just visit them
  = link_to "here.", surveyor.view_my_survey_path(response_set_code: @response_set.access_code, survey_code: @survey.access_code)

%br
%br
  = link_to 'Back', instances_path