config/routes.rb
Festivus::Application.routes.draw do
  resources :contacts
  resources :events

  devise_for :users

  resources :questionnaires, only: [:index, :show, :new, :create, :destroy] do
    match 'parse' => 'questionnaires#parse', as: "parse"
  end

  resources :instances, controller: "QuestionnaireInstances", only: [:show, :new, :create, :destroy]

  match 'instances' => 'questionnaire_instances#index', as: "instances"
  match 'instances/:id/send_reminder' => 'questionnaire_instances#remind', as: "send_reminder"

  as :user do
    get "/login" => "devise/sessions#new"
    delete "/logout" => "devise/sessions#destroy"
  end

  authenticated :user do
    root to: 'home#index', as: :authenticated_root
  end
  root to: 'home#index'

  mount Surveyor::Engine => '/surveyor', as: 'surveyor'

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

end

app/views/shared/_footer.html.haml
-# %p &copy; p&c development

app/views/shared/_form_field.html.haml
- error_class = object.errors.has_key?(field) ? 'error'  : ''
.control-group{:class => (error_class)}
  = builder.label field, :class => 'control-label'
  .controls
    -# *(opts.unshift(field)) adds fields to opt array and explodes to method args
    = builder.send(type, *(opts.unshift(field)))
    - if object.errors.has_key? field
      %span.help-inline= object.errors[field].first

app/views/shared/_header.html.haml
.navbar.navbar-default.navbar-fixed-top
  .container-fluid
    .navbar-header
      %a.navbar-brand(href='/') Festivus
    .navbar-collapse.collapse
      %ul.nav.navbar-nav
        %li= link_to 'Home', '/'
      %ul.nav.navbar-nav.navbar-right
        - if user_signed_in?
          %li.dropdown
            = link_to "#", { class: 'btn', 'data-toggle' => 'dropdown' } do
              %i{ class: 'glyphicon glyphicon-user'}
              %span.caret

            %ul.dropdown-menu
              %li= link_to "sign out", destroy_user_session_path, method: 'delete'

app/views/shared/_notifications.html.haml
.row.notifications
  - flash.each do |name, msg|
    %div.alert.fade.in{ "data-alert" => "alert", :class => to_twitter_type(name) }
      %a.close{ :href => "#", "data-dismiss" => "alert" } x
      = msg

app/views/shared/_question.html.haml
-# TODO: js for slider
- rg ||= nil
- renderer = q.renderer(g ||= nil)
- disabled = defined?(disableFlag) ? disableFlag : false
- unless q.display_type == "hidden"
  = f.inputs q_text(q, @render_context, I18n.locale), :id => rg ? "q_#{q.id}_#{rg}" : "q_#{q.id}", :class => "q_#{renderer} #{q.css_class(@response_set)}" do
    %span.help= q.help_text_for(@render_context, I18n.locale)
    - case renderer
    - when  :image, :label, :default_label, :inline_label, :repeater_label
    - when :dropdown, :inline_dropdown, :default_dropdown, :slider, :repeater_dropdown
      - r = response_for(@response_set, q, nil, rg)
      - i = response_idx
      = f.semantic_fields_for i, r do |ff|
        = ff.input :question_id, :as => :quiet
        = ff.input :response_group, :as => :quiet, :value => rg if g && g.display_type == "repeater"
        = ff.input :api_id, :as => :quiet
        = ff.input :answer_id, :as => :select, :collection => q.answers.map{|a| [a.text, a.id]}, :include_blank => (renderer != :slider), :label => q.text, :input_html => { :disabled => disabled }
    - else # :default, :inline, :inline_default
      - if q.pick == "one"
        - r = response_for(@response_set, q, nil, rg)
        - i = response_idx  # increment the response index since the answer partial skips for q.pick == one
        = f.semantic_fields_for i, r do |ff|
          = ff.input :question_id, :as => :quiet
          = ff.input :response_group, :as => :quiet, :value => rg if g && g.display_type == "repeater"
          = ff.input :api_id, :as => :quiet
      - q.answers.each do |a|
        - next if (q.pick == "one" or q.pick == "any") and disabled and @response_set.responses.where( :question_id => q.id, :answer_id => a.id).empty?
        = render a.custom_renderer || '/partials/answer', :q => q, :a => a, :f => f, :rg => rg, :g => g, :disableFlag => disabled

app/views/shared/_sidebar.html.haml
.col-sm-3.col-md-2.sidebar
  %ul.nav.nav-sidebar
    %li
      = link_to events_path do
        %i{ class: 'glyphicon glyphicon-calendar'}
        Events
    %li
      = link_to questionnaires_path do
        %i{ class: 'glyphicon glyphicon-question-sign'}
        Questionnaires
    %li
      = link_to contacts_path do
        %i{ class: 'glyphicon glyphicon-user'}
        Contacts
    %li
      = link_to instances_path do
        %i{ class: 'glyphicon glyphicon-th-large'}
        Instances