config/routes.rb
Festivus::Application.routes.draw do
  resources :contacts
  resources :events

  devise_for :users

  resources :questionnaires, only: [:index, :show, :new, :create, :destroy] do
    match 'parse' => 'questionnaires#parse', as: "parse"
  end

  resources :instances, controller: "QuestionnaireInstances", only: [:show, :new, :create, :destroy]

  match 'instances' => 'questionnaire_instances#index', as: "instances"
  match 'instances/:id/send_reminder' => 'questionnaire_instances#remind', as: "send_reminder"

  as :user do
    get "/login" => "devise/sessions#new"
    delete "/logout" => "devise/sessions#destroy"
  end

  authenticated :user do
    root to: 'home#index', as: :authenticated_root
  end
  root to: 'home#index'

  mount Surveyor::Engine => '/surveyor', as: 'surveyor'

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def thanks
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.haml
.jumbotron
  -if not user_signed_in?
    .hero-unit
      %h1 Festivals for the Rest of Us
      .lead
        You must sign in or sign up before you can access our super sweet, top secret content.
      .row-fluid
        = link_to "Login", new_user_session_path, :class => "btn btn-success"
        = link_to "Sign Up", new_user_registration_path, :class => "btn btn-primary"
  - else
    .well
      %span
        %h2 Welcome to Festivus
        %h5 Festival Planning for the "Rest of Us."

      %p
        This application has been designed to provide event planners the ability
        to define, gather, and report on information about vendors, venues and
        other parties involved in throwing the event.

        Currently you can:
        %ul
          %li= link_to "Create Questionnaires", new_questionnaire_path
          %li= link_to "Create Instances of a Questionnaire", questionnaires_path

app/views/home/thanks.html.haml
Thanks! You're event coordinator should be contacting you shortly.