config/routes.rb
Festivus::Application.routes.draw do
  resources :contacts
  resources :events

  devise_for :users

  resources :questionnaires, only: [:index, :show, :new, :create, :destroy] do
    match 'parse' => 'questionnaires#parse', as: "parse"
  end

  resources :instances, controller: "QuestionnaireInstances", only: [:show, :new, :create, :destroy]

  match 'instances' => 'questionnaire_instances#index', as: "instances"
  match 'instances/:id/send_reminder' => 'questionnaire_instances#remind', as: "send_reminder"

  as :user do
    get "/login" => "devise/sessions#new"
    delete "/logout" => "devise/sessions#destroy"
  end

  authenticated :user do
    root to: 'home#index', as: :authenticated_root
  end
  root to: 'home#index'

  mount Surveyor::Engine => '/surveyor', as: 'surveyor'

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

end

app/models/event.rb
class Event < ActiveRecord::Base
  attr_accessible :description, :title, :when, :where

  belongs_to :user
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  respond_to :html, :xml, :json

  def index
    @events = Event.all

    if !@events.empty?
      respond_with(@events)
    else
      render :empty
    end
  end

  def show
    @event = Event.find(params[:id])
    respond_with(@event)
  end

  def new
    @event = Event.new
    respond_with(@event)
  end

  def create
    @when = params[:event][:when]
    @date = DateTime.strptime(@when, "%m/%d/%Y")

    @event = Event.new(params[:event].merge({when: @date}))
    @event.user = current_user

    respond_with(@event) do |format|
      if @event.save
        flash[:notice] = 'Event was succesfully created.'
        format.html { redirect_to @event }
        format.json { render json: @event, status: :created, location: @event }
      else
        flash[:error] = @event.errors
        format.html { render action: "new" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    respond_with(@event)
  end
end

app/views/events/_form.html.haml
.well
  = form_for @event, html: { id: 'event-form' } do |e|
    %fieldset
      = bootstrapped_field(e, @event, :text_field, :title)
      = bootstrapped_field(e, @event, :text_area, :description)
      = bootstrapped_field(e, @event, :text_field, :where)

    .control-group
      = e.label :when, class: "control-label"
      .controls#datetime-picker.input-append
        = e.text_field :when
        %span.add-on
          %i{ :data => {:time_icon => "icon-time", :date_icon => "icon-calendar"} }

    .actions
      = e.submit 'Create', class: "btn btn-primary"

- content_for :javascript do
  :javascript
    $(function() { $('#datetime-picker').datetimepicker({ language: 'en', pick12HourFormat: true }); });

app/views/events/edit.html.haml
%h1 Editing Event

= render 'form'
= link_to 'Show', @event

app/views/events/empty.html.haml
%h3
  No events have been created.
  = link_to 'Create', new_event_path
  your first event.

app/views/events/index.html.haml
%h1 Upcoming Events

%table.table.table-striped.table-condensed
  %thead
    %tr
      %th Title
      %th Description
      %th When
      %th Where
      %th

  %tbody
    - @events.each do |e|
      %tr
        %td= link_to e.title, event_path(e)
        %td= e.description
        %td= e.when
        %td= e.where
        %td= link_to 'Destroy', e, :method => :delete, :data => { :confirm => 'Are you sure?' }, class: "btn btn-xs btn-danger"
%br

= link_to 'New Event', new_event_path, class: "btn btn-primary"

app/views/events/new.html.haml
%h1 New Event

= render 'form'

app/views/events/show.html.haml
%h4 Fields
.well
  %p
    %b Title:
    = @event.title
  %p
    %b Description:
    = @event.description
  %p
    %b When:
    = @event.when
  %p
    %b Where:
    = @event.where